from tkinter import*
root = Tk()
root.geometry("361x381")
root.title('calucator')
root.resizable(0,0)
def button_clk(num):
    global expression
    expression = expression +str(num)
    input_text.set(expression)
def bt_clear():
    global expression
    expression = ' '
    input_text.set(' ')
def bt_equal():
    global expression
    result = str(eval(expression))
    input_text.set(result)
    expression = ' '
expression=' '
input_text = StringVar()  
display = Entry(root,bd=30,bg = 'powder blue',font=("arial",20,"bold"),textvariable=input_text,justify="right")
display.grid(row=0,columnspan=4)  
btn_7 = Button(root,text="7",font=('arial',12,'bold'),bd = 12,height=2,width = 6,command=lambda:button_clk(7))    
btn_7.grid(row=1,column=0) 
btn_8 = Button(root,text="8",font=('arial',12,'bold'),bd = 12,height=2,width = 6,command=lambda:button_clk(8))    
btn_8.grid(row=1,column=1)
btn_9 = Button(root,text="9",font=('arial',12,'bold'),bd = 12,height=2,width = 6,command=lambda:button_clk(9))    
btn_9.grid(row=1,column=2)
btn_add = Button(root,text="+",font=('arial',12,'bold'),bd = 12,height=2,width = 6,command=lambda:button_clk("+"))    
btn_add.grid(row=1,column=3)
btn_6 = Button(root,text="6",font=('arial',12,'bold'),bd = 12,height=2,width = 6,command=lambda:button_clk(6))    
btn_6.grid(row=2,column=0) 
btn_5 = Button(root,text="5",font=('arial',12,'bold'),bd = 12,height=2,width = 6,command=lambda:button_clk(5))    
btn_5.grid(row=2,column=1)
btn_4 = Button(root,text="4",font=('arial',12,'bold'),bd = 12,height=2,width = 6,command=lambda:button_clk(4))    
btn_4.grid(row=2,column=2)
btn_sub = Button(root,text="-",font=('arial',12,'bold'),bd = 12,height=2,width = 6,command=lambda:button_clk("-"))    
btn_sub.grid(row=2,column=3)
btn_3 = Button(root,text="3",font=('arial',12,'bold'),bd = 12,height=2,width = 6,command=lambda:button_clk(3))    
btn_3.grid(row=3,column=0) 
btn_2 = Button(root,text="2",font=('arial',12,'bold'),bd = 12,height=2,width = 6,command=lambda:button_clk(2))    
btn_2.grid(row=3,column=1)
btn_1 = Button(root,text="1",font=('arial',12,'bold'),bd = 12,height=2,width = 6,command=lambda:button_clk(1))    
btn_1.grid(row=3,column=2)
btn_mul = Button(root,text="*",font=('arial',12,'bold'),bd = 12,height=2,width = 6,command=lambda:button_clk("*"))    
btn_mul.grid(row=3,column=3)
btn_c = Button(root,text="clear",font=('arial',12,'bold'),bd = 12,height=2,width = 6,command=bt_clear)    
btn_c.grid(row=4,column=0) 
btn_0 = Button(root,text="0",font=('arial',12,'bold'),bd = 12,height=2,width = 6,command=lambda:button_clk(0))    
btn_0.grid(row=4,column=1)
btn_div = Button(root,text="/",font=('arial',12,'bold'),bd = 12,height=2,width = 6,command=lambda:button_clk("/"))    
btn_div.grid(row=4,column=2)
btn_eql = Button(root,text="=",font=('arial',12,'bold'),bd = 12,height=2,width = 6,command=bt_equal)    
btn_eql.grid(row=4,column=3)
root.mainloop()